=== miltonizer/miltons_twitch_quake/ezquake/help/xsd/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="document">
		<xs:annotation>
			<xs:documentation>document</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="head">
					<xs:annotation>
						<xs:documentation>document information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="date" type="xs:date" minOccurs="0"/>
							<xs:element name="authors" minOccurs="0">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="author">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="email" type="xs:string" minOccurs="0"/>
													<xs:element name="im" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="body" type="blocks">
					<xs:annotation>
						<xs:documentation>document content</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="blocks" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="section"/>
			<xs:element ref="h"/>
			<xs:element ref="p"/>
			<xs:element ref="list"/>
			<xs:element ref="dict"/>
			<xs:element ref="hr"/>
			<xs:element ref="pre"/>
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="h">
		<xs:annotation>
			<xs:documentation>header (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="inline">
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:annotation>
			<xs:documentation>paragraph (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:annotation>
			<xs:documentation>list (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="dict">
		<xs:annotation>
			<xs:documentation>dictionary (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="di"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="style" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="block"/>
						<xs:enumeration value="inline"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="hr" type="empty">
		<xs:annotation>
			<xs:documentation>horizontal rule (block)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pre">
		<xs:annotation>
			<xs:documentation>preformatted text (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="inline" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="color" type="inline">
		<xs:annotation>
			<xs:documentation>coloured (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="em" type="inline">
		<xs:annotation>
			<xs:documentation>emphasis (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="a">
		<xs:annotation>
			<xs:documentation>anchor (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:annotation>
			<xs:documentation>image (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="src" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="br" type="empty">
		<xs:annotation>
			<xs:documentation>line break (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="sp" type="empty">
		<xs:annotation>
			<xs:documentation>space (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="empty">
		<xs:restriction base="xs:string">
			<xs:length value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="li" type="blocks">
		<xs:annotation>
			<xs:documentation>list entry</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="di">
		<xs:annotation>
			<xs:documentation>dictionary entry</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="inline"/>
				<xs:element name="description" type="blocks"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="section">
		<xs:annotation>
			<xs:documentation>section (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="title" type="xs:string" use="required"/>
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miltonizer/miltons_twitch_quake/ezquake/help/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/document.xsd">
	<head>
		<title>ezQuake Manual - QuakeWorld for Freshies</title>
		<date>2004-10-16</date>
	</head>
	<body>
		<h align="center">QuakeWorld for Freshies</h>
		<hr />
		<p>Welcome to QuakeWorld! This manual covers most aspects of what you need to know in order to play, to enjoy and to be successful with this game called QuakeWorld. This is a work in progress and is regularly updated.</p>
		<br />
		<h>Table of Contents</h>
			<list>
				<li><h>Introduction</h>
					<list>
						<li><a href="help/manual/welcome.xml">Welcome</a></li>
						<li><a href="help/manual/external_resources.xml">External resources</a></li>
						<li><a href="help/manual/faq.xml">Frequently Asked Questions</a></li>
					</list>
				</li>
			</list>
			<list>
			<li><h>Entering QuakeWorld</h>
				<list>
						<li><a href="help/manual/quick.xml">Quick guide</a>
							<list>
								<li>Downloading QW</li>
								<li>Connecting to a server</li>
							</list>
						</li>
						<li><a href="help/manual/concept.xml">The concept of the game</a></li>
						<li><a href="help/manual/what_qw.xml">What is QuakeWorld?</a>
							<list>
								<li>NetQuake</li>
								<li>QuakeWorld</li>
								<li>Custom QW clients</li>
							</list>
						</li>
						<li><a href="help/manual/links.xml">Where is the Quake World?</a>
							<list>
								<li>Places to know</li>
								<li>Places to be</li>
							</list>
						</li>	
					</list>
					<list>		
						<li><a href="help/manual/items.xml">Items</a>
							<list>
								<li>Weapons</li>
								<li>Ammo and health</li>
								<li>Armors</li>
								<li>Powerups</li>
							</list>
						</li>					
						<li><a href="help/manual/maps.xml">Maps</a>
							<list>
								<li>Deathmatch maps</li>
								<li>Episode maps</li>
								<li>Custom maps</li>
							</list>
						</li>
					</list>
				</li>
			</list>
			<list>
				<li><h>How to play QuakeWorld</h>
					<list>
						<li><a href="help/manual/important_commands.xml">Important commands</a></li>
						<li><a href="help/manual/jumping.xml">QuakeWorld jumping</a></li>
						<li><a href="help/manual/ping_lag.xml">Ping and lag</a></li>
						<li><a href="help/manual/etiquette.xml">QuakeWorld etiquette</a></li>					
					</list>
				</li>
			</list>
			<list>
				<li><h>Strategies</h>
					<list>
						<li><a href="help/manual/teamplay.xml">Teamplay manual</a></li>
						<li><a href="help/manual/dm2.xml">DM2 overview</a></li>
						<li><a href="help/manual/dm3.xml">DM3 overview</a></li>
						<li><a href="help/manual/dm6.xml">DM6 overview</a></li>		
						<li><a href="help/manual/e1m2.xml">E1M2 overview</a></li>
						<li><a href="help/manual/e3m7.xml">E3M7 overview</a></li>					
					</list>
				</li>
			</list>
			<list>
				<li><h>Configuration and settings</h>
					<list>
						<li><a href="help/manual/structure.xml">Files and structure</a>
							<list>
								<li>Quake and QW directory structures</li>
								<li>Quake and QW files</li>
								<li>Quake cfg structure</li>
							</list>
						</li>
						<li><a href="help/manual/cmdline.xml">Command line parameters</a></li>			
						<li><a href="help/manual/commands.xml">Commands and variables</a>
							<list>
								<li>QW console</li>
								<li>General commands</li>
								<li>Advanced commands</li>
							</list>
						</li>			
						<li><a href="help/manual/scripts.xml">Scripts</a>
							<list>
								<li>Weapon scripts</li>
								<li>Jumping scripts</li>
							</list>
						</li>			 
						<li><a href="help/manual/video.xml">Video/graphics settings</a>
							<list>
								<li>OpenGL or software?</li>
								<li>OpenGL settings</li>
								<li>Software settings</li>
								<li>Tweaking</li>
							</list>
						</li>		 
						<li><a href="help/manual/qizmo.xml">Qizmo</a>
							<list>
								<li>What is a proxy?</li>
								<li>Using Qizmo</li>
							</list>
						</li>
					</list>
				</li>
			</list>
			<list>
				<li><h>Miscellaneous</h>
					<list>
						<li><a href="help/manual/server.xml">Server manual</a>
							<list>
								<li>Setting up a server</li>
								<li>Modifications</li>
								<li>Controlling</li>
								<li>Console variables and commands</li>
								<li>Command line parameters</li>
							</list>
						</li>
						<li><a href="help/manual/history.xml">Quake history</a>
							<list>
								<li>Quake/QW version history</li>
								<li>Leagues and tournaments</li>
								<li>Events</li>
								<li>Mods and proxies </li>
							</list>
						</li>
					 </list>
				 </li>
		 	</list>
		<br />
		<color><a href="http://www.challenge-smackdown.com/qwguide/">QuakeWorld for Freshies</a> courtesy of Mirco "Apollyon" Strissel. Used under permission.</color>
		</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/teamplay.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - Teamplay manual</title>
		<date>2003-10-07</date>
	</head>
	<body>
		<h align="center">Teamplay manual</h>
		<br />
		<pre>
		This guide was written by bunny and originally posted <a href="http://www.quake.ie/comments.asp?item=1524">here</a>. It explains the most basic parts of QW teamplay concentrating on the map dm3.
		</pre>
		<h>Introduction</h>
		<p>QW teamplay is very fast and old fashioned (no fancy teamoverlays). You have to think quickly, react quickly and situations can change quite suddenly. One player can hold an area and a team (of 4) can lock down an entire map.</p>
		<h>Spawning</h>
		<p>As a player you spawn almost instantly after you die, you have 100 health and you can be killed straight away by one shot from a Rocket Launcher (RL) or a Grenade Launcher (GL). When a game starts, spawning players often telefrag each other because on some QW maps there are less spawn points than there are total players. Everything is there when you first spawn, including Quad, Pent and Eyes.</p>
		<h>Respawn times</h>			
			<list>
				<li><color>Armor</color> - 20 seconds.</li>
				<li><color>Health</color> - 20 seconds.</li>
				<li><color>Weapons</color> - 30 seconds.</li>
				<li><color>Ammo</color> - 30 seconds.</li>
				<li><color>Quad Damage</color> - Lasts 30 seconds, spawns 30 seconds later (it's always there every minute).</li>
				<li><color>Pentagram of Protection</color> - Lasts 30 seconds, spawns 4 mins 30 seconds later (so it's there every 5 mins).</li>
				<li><color>Ring of Shadows magic</color> - Same as Pent.</li>
				<li><color>Megahealth</color> - 20 seconds after it has run out.</li>
			</list>
			<h>Starts</h>
			<p>Starts can be learned for each map. For example Yellow Armor (YA) spawn on DM3 should grab the YA, go through teleport, jump out and land on the Pent. He should encounter either a teammate or enemy jumping from the Lifts spawn for the Pent aswell. Getting a good start can win you the game. The best way to prepare a start is by figuring out the best route for each spawn and by anticipating enemy spawns. Your team should be prepared if the enemy gets the 4 best spawns (fullstart).</p>
			<h>Getting control</h>
			<p>Your team must get RLs or deny them to the enemy, thats the main thing. Once a team member gets an RL he must get to armor.</p>
			<p>Once he has armor he can: </p>
			<list>
				<li>Hold that area.</li>
 				<li>Get powerups.</li>
 				<li>Help teammates to get a weapon/armor.</li>
			</list>
			<p>Unlike Quake 3, in QW one guy with an RL can hold an entire area. For instance, one of your teammates can hold Red Armor (RA) on DM3 with an RL quite easily - on his own. If he positions himself just right he can watch all the entrances. Health and ammo are available nearby. He can supply the team with that RA, he is denying it the enemy, he can get to Quad in about 3 or 4 seconds, he can hold packs for teammates. It's an important position. Once he has RA, the team can concentrate on taking the other parts of the map, once your entire team has RL's (or Lightning Guns) they should be able to take control of the map once they all move into the optimum positions.</p>
			<h>Set tactics</h>
			<p>There are generally set tactics for holding/controlling a map. The most played teamplay maps in QW are DM3, DM2 and E1M2 (aka The Big Three - TB3). Denying armor to the enemy was really perfected by Clan 9 when they destroyed the American clan Deathrow. Deathrow thought the most important areas on the maps were those areas which contained the best weapons. However by constant boomstick charging and gaining control of the armor areas of the maps, Clan 9 were able to deny all armor to the Americans who had little protection and lost their weapons in packs to the enemy.</p>
			<p>On <a href="help/manual/dm3.xml">DM3</a> and <a href="help/manual/e1m2.xml">E1M2</a> the RL area is not of strategic importance, only very skilled teams will try and run it. The armor is the key to both those maps.</p>
			<p><a href="help/manual/dm2.xml">DM2</a> is slightly different. Although tactics vary alot on this map, good teams will often secure the lower YA/tele first, thus blocking off High RL/GL/Mega/Quad which enemy can only get to by rocketjumping. DM2 is small enough to attempt a complete lockdown of the map, leaving only one small area which is not covered (Bigroom - which contains 2 YA's).</p>
			<p>Tactics are up to the skill of the team. Make them too complicated or advanced and the guys on your team won't be able to handle it. Make them too simplified and they may not be enough to beat the enemy team.</p>
			<h>General rules</h>
			<p>Here are the basic rules of teamplaying:</p>
			<list>
				<li>
					<h>Think of the team - not yourself.</h>
					Forget how many kills you are on, don't try to get the top score. Everything you do is for the good of the team.
				</li>
				<li>
					<h>Read team messages (and respond)</h>
					Learn to read these. Who wants to be replaced, who needs help, where is a pack, etc (don't spam team messages)
				</li>
				<li>
					<h>Read death messages</h>
					These tell you a lot about what is going on. If your YA teammate says 'took YA' followed by 'teammate rides enemyguy's rocket' you know an enemy has just taken the YA area. But YA isn't gonna be in for a while, so it's best to attack that area quickly. They give you a good idea of the whole situation.
				</li>				
				<li>
					<h>Be aware</h>
					This encompasses a lot of situations. You shouldn't need to be told to go for Quad, you should know when it is, when Pent is, you should always be aware of what your teammates have and where they are. Good nonspammed teamtalk will help you out a lot here.
				</li>				
				<li>
					<h>Don't take important items on low health</h>
					Stop doing this. Check if a healthier teammate is close by, if not, take it. 
				</li>				
				<li>
					<h>Stop snatching weapons/armor you already have</h>
					Stop doing this. Check if a teammate needs it, take it if enemy are very close. Taking an RL when you already have one is a waste when one of your teammates doesn't have one. You should advertise it, anyone who wants it should hit the bind "coming from..". Keep close so you can snatch it if an enemy comes for it.
				</li>				
				<li>
					<h>Don't block or hang close to teammates</h>
					Always leave your teammate lots of space, stand apart, don't run together, stay within viewing distance, stay far away from friendly quad. Standing too close causes you to block them when they want to back off and also causes team damage.
				</li>				
				<li>
					<h>Learn to attack properly</h>
					You may have lost control on a map and the enemy team might be spawnfragging you. Learn to coordinate your boomstick attacks on one guy in one part of the map. Learn to dodge wierdly and jump in close causing him to take splash damage from his RL or force him to switch to boomstick. Very few RL guys can withstand 4 enemy constantly boomsticking them. Triangulate your fire aswell so that you don't shoot up your teammates, move away from each other.
				</li>				
				<li>
					<h>Learn to hide properly</h>
					You may have to hide from an enemy quad or when you are low on health with an RL. It is possible to sneak to less dangerous parts of the maps (e.g. SNG on DM3, or Start Room on E1M2)
				</li>				
				<li>
					<h>Ammo</h>
					Watch your ammo. Don't take too much ammo, especially rockets, leave it for teammates.
				</li>				
				<li>
					<h>Packs</h>
					Anyone who dies leaves a pack with the last weapon fired and all ammo they have picked up before their death. If they have a shotgun script (switches to boomstick or axe when the RL is not being fired) then weapons in packs are harder to come by. It's possible to come by a pack that contains 99 rockets and 100 cells. Useless boomstick packs in a room can be used as bait, packs can be used as sources of ammunition, and a pack with an RL in it is a priority for teammates.
				</li>				
				<li>
					<h>Locs / teamtalk</h>
					Agree to use the same <a href="http://maps.quakeworld.nu/locs/download/">locs</a> (location files for maps) as the rest of your team. 
					Also use the same teamtalk format. Don't make teamtalk too fancy. Bind the most important teamtalk messages closest to your movement and weapon keys.
					<p><color>Teamtalk commands in order of importance are:</color></p><list>
						<li>The point command ('pack -> bridge', 'ra -> Ra', etc).</li>
						<li>The report command (Armor/Health, best weapon, and Powerups).</li> 
						<li>'help -> x', 'replace x', 'coming -> x'.</li>
						<li>'secure -> x, 'took x -> y', 'get quad/pent'.</li> 
						<li>'you take', 'cancel that'.</li>
					</list>					
				</li>				
			</list>
	</body>
</document>
