=== miltonizer/miltons_twitch_quake/ezquake/help/xsd/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="document">
		<xs:annotation>
			<xs:documentation>document</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="head">
					<xs:annotation>
						<xs:documentation>document information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="date" type="xs:date" minOccurs="0"/>
							<xs:element name="authors" minOccurs="0">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="author">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="email" type="xs:string" minOccurs="0"/>
													<xs:element name="im" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="body" type="blocks">
					<xs:annotation>
						<xs:documentation>document content</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="blocks" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="section"/>
			<xs:element ref="h"/>
			<xs:element ref="p"/>
			<xs:element ref="list"/>
			<xs:element ref="dict"/>
			<xs:element ref="hr"/>
			<xs:element ref="pre"/>
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="h">
		<xs:annotation>
			<xs:documentation>header (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="inline">
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:annotation>
			<xs:documentation>paragraph (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:annotation>
			<xs:documentation>list (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="dict">
		<xs:annotation>
			<xs:documentation>dictionary (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="di"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="style" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="block"/>
						<xs:enumeration value="inline"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="hr" type="empty">
		<xs:annotation>
			<xs:documentation>horizontal rule (block)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pre">
		<xs:annotation>
			<xs:documentation>preformatted text (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="inline" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="color" type="inline">
		<xs:annotation>
			<xs:documentation>coloured (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="em" type="inline">
		<xs:annotation>
			<xs:documentation>emphasis (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="a">
		<xs:annotation>
			<xs:documentation>anchor (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:annotation>
			<xs:documentation>image (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="src" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="br" type="empty">
		<xs:annotation>
			<xs:documentation>line break (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="sp" type="empty">
		<xs:annotation>
			<xs:documentation>space (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="empty">
		<xs:restriction base="xs:string">
			<xs:length value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="li" type="blocks">
		<xs:annotation>
			<xs:documentation>list entry</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="di">
		<xs:annotation>
			<xs:documentation>dictionary entry</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="inline"/>
				<xs:element name="description" type="blocks"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="section">
		<xs:annotation>
			<xs:documentation>section (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="title" type="xs:string" use="required"/>
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/cmdline.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - Command line</title>
		<date>2003-10-07</date>
	</head>
	<body>
		<h align="center">Command line</h>
		<br />
		<p><color>For command line confugartion use a program called ezstart.exe</color>. QW can of course be started by simply doubleclicking on the executable, but there are a few command line parameters which should be used to make QW run even better and which can sometimes solve problems as well. The easiest way is to create a shortcut or even better a batch (.bat) file for starting QW. The most important command line parameters are described below:</p>
			<list>
			<li>
				<h>-width xxx and -height xxx</h>
				These set the video resolution (by default software QW will start in 320x200 and gl QW in 640x480). To see all the resolutions your graphic board supports you have to type "vid_describemodes" at the console. The modes available depend on your type of board, driver version and your systems ram.
			</li>
			<li>
				<h>-bpp 32</h>
				This will start QW with 32 bit colors. When running software QW you should set it to 8.
			</li>
			<li>
				<h>-heapsize [x]</h>
				This allocates the given amount of ram to QW in bytes. By default QW won't take more than 16mb of ram but when you have more than 32mb system ram you should force it to take more since the more ram it can use the less hd (and sometimes video or sound) lag you will have.
			</li>
			<li>
				<h>-dinput</h>
				Turning directinput on will make your mouse movement much smoother.
			</li>
			<li>
				<h>-zone 8192</h>
				This increases your keys and message memory buffer from default of 48kb to 8192kb. Your keys will respond much better.
			</li>
			<li>
				<h>-window</h>
				When you put this in front of the -width and -height command it might solve some problems you might have with certain video modes. QW does not run in a window but even lower resolutions will be a bit slower than usually.
			</li>
			<li>
				<h>-dibonly</h>
				This command often solves problems that occur with software QW in combination with modern GeForce graphic cards, like screen turning black when quitting QW or the colors on the desktop look wrong.
			</li>									
			</list>
			<h>So your QW starting command line could look something like this then:</h>
			<p>ezquake-gl.exe -noscripts -ruleset smackdown -heapsize 81920 -zone 8192 -sndbits 16 -sndspeed 48000 -dinput -m_smooth -bpp 16 -width 640 -conwidth 640 +set vid_displayfrequency 85 +set s_khz 44</p>
			<p>There are a few more commands which are not commonly used. For an explanation on those refer to the Quake and QW readme files.</p>
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/concept.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - The concept of the game</title>
		<date>2004-10-16</date>
	</head>
	<body>
		<h align="center">The concept of the game</h>
		<br />
		<p>Quake is a game which can be classified as a shooter. In this shooter you can see everything from the first person point of view, that is as through the eyes of your player character, or from the third point of view (so you always see Ranger's back). That naturally makes the environment in which you play three dimensional. Most of the time you are moving through some sort of maze that represents an ancient castle, a tomb, sewers or simpley a building. That depends on the setting of the respective game (QW has a somewhat "medieval" setting). Along your way you encounter a lot of enemies which you dispatch with the weapons you found previously. Besides the weapons there are also other items to pick up like health, ammunition or powerups which help you on your quest.</p>
		<p>The goal of the game depends a lot on which mode you play. In single player the goal is more or less to find the exit of the maze. Before reaching that you usually have to kill a boss monster blocking the exit. Often you have to solve some puzzles as well, like finding a key to open a door.</p>
		<br />
		<p>In multiplayer the concept is much different. In short words it is to kill the enemy player.There are many different styles though. In deathmatch or "free for all" two or more players kill each other until someone reaches the fraglimit that is has killed his enemies a certain number of times. Once the limit is reached you start over, either on the same map or a different one. In duel or 1on1 you only have a single enemy at the same time. Usually you play for like 10 minutes. Whoever gets the most frags(kills) wins the duel. In contradiction to raw deathmatch this mode requires much more knowledge about various aspects of the game.</p>
		<p>Teamplay means that you play together with your team against another team. This can be 2on2, 4on4 or even 10on10. Teamplay is perhaps the most difficult mode to master in a shooter since you not only have to care about yourself but you also have to pay a lot of attention towards what your teammates are doing. This is if you want your team to win of course.</p>
		<br />
		<p>For a newbie QW might not be the best game to try because it is very hard to get into it. However here in our guide we will provide you with all the information you need and it is worth the effort. QW is considerably better than the modern shooter games when it comes down to what a game is all about: gameplay.</p>
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - Maps</title>
		<date>2004-10-16</date>
	</head>
	<body>
		<h align="center">Maps</h>
		<br />
		<p>Quake comes with more than 30 maps. Most of these are so called "episode" maps because they were gathered in the four episodes of single player mode. They can all be played in multiplayer though, some of them are really good maps in fact while others are just too large or not good enough. The game also comes with six maps specifically designed for deathmatch. There are 5 maps that stand out of all others and which are played the most. These are dm2, dm3, dm4, dm6 and e1m2. They are briefly explained below.</p>
		<p>There are also thousands of custom maps available for Quake. Many are regularly used but there is only a handful which also get played in competitions. Sooner or later you will encounter the term "the big three" (or tb3). This means dm2, dm3 and e1m2 which are the most used maps in deathmatch teamplay. For playing strategies look in the strategies section.</p>
		
		<h>DM2: Claustrophobopolis</h>
		<p>Claustrophobia is the abnormal fear of being in an enclosed place. This is a feeling you can easily get when you are on this map the first time. It features many tight corridors, low ceilings and a complex design which makes it difficult to understand at first. It also has many switches, secrets and moving platforms. There is also a lot of deadly lava on the map unwary and unexperienced players often fall victim to. But once you understand the layout of the map you will like it because its perfect fighting grounds. Dm2 is both a popular map in teamplay as well as duel.</p>

		<h>DM3: The Abandoned Base</h>
		<p>Dm3 is a rather large map with many big rooms and a large watery area that has all the weapons and powerups Quake has. It seems quite complex at the first glance and without good map knowledge you can easily feel lost on it. But certain trickjumps and techniques make it smaller that it actually is. The fame of this level as a teamplay map goes even beyond the QW scene itself, its truly a classic and feels just right. On the other hand it is not much fun in 1on1 due to its sheer size.</p>
		
		<h>DM4: The Bad Place</h>
		<p>Being truly a bad place for newbies you can expect to finish your first games here with a negative score. The bottom of this rather small map has lots of the dreaded lava and experienced players know how to get you in there just to humiliate you. It is compromised of a large room with some smaller rooms surrounding and exiting into it. There are a few teleporters as well poviding even more connections which in the beginning often confuse new players. But in the end the map and how to play it in general is rather easily learned. As much as dm3 is praised as classic teamplay map, dm4 is perhaps the duel map of Quake.</p>
		
		<h>DM6: The Dark Zone</h>
		<p>Despite its name this is a rather brightly lit map which is perhaps the easiest to understand. It is popular in all modes of play, deathmatch, duel and teamplay, but opinions wether it is a good map for a certain mode (especially teamplay) differ a lot. What everybody agrees on is that it is a very good duel map. In my opinion it is perfect for understanding Quake, in fact everything i learned about Quake i learned on dm6 in the end, be it how to camp, the importance of armors, how to control a map, how to rocketjump or how to bunny hop.</p>
		
		<h>E1M2: Castle of the Damned</h>
		<p>A popular teamplay map that is also a good duel map. This level is one of the few exceptions where the rocketlauncher is not as important as it usually is. In fact you can afford not to camp or go for it all the time. The supernailgun together with the yellow armor makes up a powerful combination here. Usually you wait for the enemy to bring you the rocketlaunchers and once you got them you are even more powerful and he in an even worse situation. Playing this map promises a lot of carnage and fun when you know how to play it. This map is usually played in 4on4 deathmatch but it is not too shabby as a duel map either. Try it 1on1 for a different experience.</p>
		
		<h>CMT4: Andromeda Nine (cmt version)</h>
		<p>Originally an old custom map that was rarely played outside of the UK it was slightly modified for the Custom Map Tournament. Although not quite as popular as "the big three" yet it is now by far the most played custom map in teamdeathmatch tournaments. The layout of this large map is easier than it might seem at the first glance. The map is dominated by a large atrium and another rather large room each of which contain one of the ever so important armors. What sets it apart from other maps is that getting the pentagram of protection requires a coordinated team effort while the Quad room can be attacked from all important areas of the map within seconds.</p>
		
		<h>Aerowalk: Aerowalk</h>
		<p>It was the Australian community who discovered this map as one of the best duel maps ever before it also got adopted in other parts of the world. Not an easy map to master Aerowalk is an epitome of verticalness. While most Quake maps have quite horizontal layouts this map is the opposite. Walkways on several levels are running around a large central area. The different levels are connected by ramps, stairs, teleporters and some sort of jumppad. You can get to any place of the map within seconds - if you know how to and if you got the necessary skills. You cannot hide here and this map probably suits the modern fast playing style of Quake best.</p>
		
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/e3m7.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - E3M7: The Haunted Halls</title>
		<date>2003-10-07</date>
	</head>
	<body>
		<h align="center">E3M7: The Haunted Halls</h>
		<br />
		<h>Introduction</h>
		<p>The Haunted Halls is a pretty small map with tight tunnels and many powerups. The respawns are easy to camp on this map, so a good clan with control can get many frags in a short time.</p>
		<br />
		<h>Items available</h>			
			<h>Weapons</h>
			<list>
				<li>2 Rocket Launchers</li>
				<li>1 Grenade Launcher</li>
				<li>1 Super Nailgun</li>
				<li>1 Nailgun</li>
			</list>
			<h>Armor</h>
			<list>
				<li>1 Red Armor</li>
				<li>2 Yellow Armors</li>				
				<li>1 Green Armor</li>
			</list>
			<h>Powerups</h>
			<list>
				<li>2 Quad damage</li>
				<li>1 Pentagram of Protection</li>
				<li>1 Ring of Shadows magic</li>
				<li>1 Ring of Shadows magic</li>
			</list>
			<br />
			<h>Important areas</h>
			<p>This map is basically laid out as a string of rooms and areas connected by a few narrow corridors. There are two areas which are far more important then the rest of the map. One of them forms one end of the 'string' and contains RL, the Ring, the Pentagram, a Quad, a Megahealth and a Yellow armor. The second important area, somwhere in the middle of the map, holds another RL, a Quad, a Megahealth and a Yellow armor. The other extreme of the playing field contains the Grenade launcher, SNG and GA but doesn't usually see much action during a game. The best use of this area is as a hide-out when things get rough in the rest of the map. The descriptions below start from here.</p>
			<list>
			<li>
				<h>GA and SNG</h>
				This area is at one end of the map. Besides the GA and the SNG there really isn't much of interest here. 
				The only way out is through a teleporter (with a Nailgun in front) that takes you to a higher level. Should you ever want to come back here, just drop down again near the teleporter.
			</li>
			<li>
				<h>GL</h>
				From the teleport exit of the GA area, a small elevator goes up one more level to a tiny room with a Grenade launcher. 
				A passage leads further to the Tower RL area. The only other way out of here is back down to the GA area. As with the GA area, unless you are hiding from your enemies you shouldn't be here.
			</li>			
			<li>
				<h>RL Tower</h>
				This is one of the two key areas. The RL is on the small 'tower' or 'castle' and can be reached by a small elevator of the side. Under this elevator, a Megahealth is hidden. Below and in front of the RL sits a Quad in a tiny alcove. In case you accidentally end up in the lava, a few stairs can help you out again if you're quick. This is a great place to camp since there are many spawns here. 
				From this place a passage leads to the Grenade launcher area. The other direction leads across the cage room to the RA and the other vital place with RL.
			</li>			
			<li>
				<h>Cage room</h>
				This room serves as the connection from the tower area to the RA. The only interesting feature is a cage in the lava. To get out of this trap, you have to shoot a switch to activate a teleport.
			</li>			
			<li>
				<h>RA stairs and Nails</h>
				The only RA of the map can be found next to a short staircase. These stairs connect the cage room to a corridor with automatic spike traps in the wall. The spikes make a lot of noise and thus anounce your arrival in the final part of the map well in advance.
			</li>				
			<li>
				<h>RL Bridge</h>
				This room is split in two by a gap filled with lava. Lifts go up to a bridge that connects the two sides. The RL sits in the middle of this bridge. In a small cubbyhole down a side, you find a Yellow armor, Megahealth and a Quad. Across the lava is the entrance to an elongated room with the Ring. 
				From the RL, you can also jump to a hidden door in the wall. Behind this resides the Pentagram. 
				As this area forms the end of the map, there is only one entrance to it: the passage with spikes to the RA.
			</li>
			</list>
			<h>Popular shortcuts</h>
			<p>This is a fairly easy map in terms of shortcuts. There is no hard individual trick or good shortcut to be learned here. One easy shortcut you can use is to rocketjump up to the Pentagram instead of going past the RL on the bridge. Another very basic shortcut is to jump across the lava below the bridge. A funny thing to try in teamplay involes the cage (which is opened by shooting at a button on the wall) in the middle of the map. Put a teammate in the cage and let another teammate look at the RL Tower direction. When the teammate sees an enemy coming through the teleport destination, shoot on the button in the cage to telefrag him.</p>
			<h>Basic strategies</h>
			<p>Like all maps, it's the eternal struggle to get the guns, armors and powerups under control. You fight until you get either of the RL areas under control and from there use a Quad to try and take over the other area. Instead of a Quad, the Pentagram can also be used to clear the tower area.</p>
			<p>Once everything is under control, the positions would be one player at the bridge RL area, one at RA, one at the tower RL area and one chasing the probably hiding enemies in the GL to exit area.</p>	
	</body>
</document>
