=== miltonizer/miltons_twitch_quake/ezquake/help/xsd/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="document">
		<xs:annotation>
			<xs:documentation>document</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="head">
					<xs:annotation>
						<xs:documentation>document information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="date" type="xs:date" minOccurs="0"/>
							<xs:element name="authors" minOccurs="0">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="author">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="email" type="xs:string" minOccurs="0"/>
													<xs:element name="im" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="body" type="blocks">
					<xs:annotation>
						<xs:documentation>document content</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="blocks" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="section"/>
			<xs:element ref="h"/>
			<xs:element ref="p"/>
			<xs:element ref="list"/>
			<xs:element ref="dict"/>
			<xs:element ref="hr"/>
			<xs:element ref="pre"/>
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="h">
		<xs:annotation>
			<xs:documentation>header (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="inline">
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:annotation>
			<xs:documentation>paragraph (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
					<xs:attribute name="align" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="center"/>
								<xs:enumeration value="right"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:annotation>
			<xs:documentation>list (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="li"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="dict">
		<xs:annotation>
			<xs:documentation>dictionary (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="di"/>
			</xs:sequence>
			<xs:attribute name="bullet" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="number"/>
						<xs:enumeration value="letter"/>
						<xs:enumeration value="big-letter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="separator" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="dot"/>
						<xs:enumeration value="par"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="style" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="block"/>
						<xs:enumeration value="inline"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="hr" type="empty">
		<xs:annotation>
			<xs:documentation>horizontal rule (block)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="pre">
		<xs:annotation>
			<xs:documentation>preformatted text (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="alt" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="inline" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="color"/>
			<xs:element ref="em"/>
			<xs:element ref="a"/>
			<xs:element ref="img"/>
			<xs:element ref="br"/>
			<xs:element ref="sp"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="color" type="inline">
		<xs:annotation>
			<xs:documentation>coloured (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="em" type="inline">
		<xs:annotation>
			<xs:documentation>emphasis (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="a">
		<xs:annotation>
			<xs:documentation>anchor (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="href" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:annotation>
			<xs:documentation>image (inline)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="src" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="br" type="empty">
		<xs:annotation>
			<xs:documentation>line break (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="sp" type="empty">
		<xs:annotation>
			<xs:documentation>space (inline)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="empty">
		<xs:restriction base="xs:string">
			<xs:length value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="li" type="blocks">
		<xs:annotation>
			<xs:documentation>list entry</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="di">
		<xs:annotation>
			<xs:documentation>dictionary entry</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="inline"/>
				<xs:element name="description" type="blocks"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="section">
		<xs:annotation>
			<xs:documentation>section (block)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="blocks">
					<xs:attribute name="id" type="xs:string" use="optional"/>
					<xs:attribute name="title" type="xs:string" use="required"/>
					<xs:attribute name="indent" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/links.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - Where is the Quake World?</title>
		<date>2004-10-16</date>
	</head>
	<body>
		<h align="center">Where is the Quake World?</h>
		<br />
		<p>Being a new player you surely not only want to know how to play and set up QW properly but also where the popular servers, the news and the tournaments are. So we will provide you with the most important adresses of Quake World.</p>
		<h>News and coverage</h>
		<list>
			<li>
				<h><a href="http://www.quakeworld.nu/">QuakeWorld.nu</a></h>
				The best portal to get news about QW. Has a crew of dedicated writers who bring you the latest QW news from all over the world, including coverage of important league/tournament games, articles, interviews, and a lot more.
			</li>
			<li>
				<h><a href="http://www.besmella-quake.com/">Besmella.Quake</a></h>
				Another QW news site, used to be swedish now in english.
			</li>
			<li>
				<h><a href="http://www.quakeworld.ru/">QuakeWorld.ru</a></h>
				Russian QuakeWorld news site, available both in russian and english versions.
			</li>			
			<li>
				<h><a href="http://members.webdeveloping.nl/~trouby/nqeu/">NetQuake Europe</a></h>
				European NetQuake community site.
			</li>			
			<li>
				<h><a href="http://www.planetquake.com/quake1/">PlanetQuake</a></h>
				Still the place for everything Quake1, especially for all sorts of files and mods.
			</li>
		</list>		
		<h>Competitions</h>
		<list>
			<li>
				<h><a href="http://www.nqr.nu/">Nations Quake Rank</a></h>
				NQR is currently the largest and most important QW 4on4 league. The league is divided into divisions based on skill. It is open for everyone, ranging from hardcore clans to complete newbie teams. Last season had over 90 teams participating!
			</li>
			<li>
				<h><a href="http://www.norrteljeporten.se/robert/rmr/news.php">Ride My Rocket</a></h>
				Ride My Rocket (RMR) is an online QuakeWorld Free For All (FFA) tournament. As the tournament's first goal is to provide fun and entertainment for everyone involved, and will not result in any substantial financial benefits for the winners, it may seem strange to have rules in the first place. However, whenever a competitive aspect is present, some rules will be necessary to make sure everyone can face eachother in a fair environment.
			</li>
			<li>
				<h><a href="http://ibc.quakeworld.nu/">International QuakeWorld Bot Challenge</a></h>
				A competition where players try to achieve best Lightning Gun efficiency.
			</li>
			<li>
				<h><a href="http://qwwc.quakeworld.nu/">QuakeWorld World Championships</a></h>
				National teams from all over the Europe and one from North America participate to win the World Championship title.
			</li>
			<li>
				<h><a href="http://duelmania.quakeworld.nu/">DuelMania</a></h>
				Currently the largest online duel tournament going on.
			</li>
			<li>
				<h><a href="http://hem.bredband.net/b246801/">Suddendeath Invitational Tournament</a></h>
				The invitational tournament which goal is equal and fun competition.
			</li>
			<li>
				<h><a href="http://www.qhlan.org/">QH-LAN</a></h>
				Held in Stockholm, Sweden, around two times each year - this is the largest and only serious QW event going on. Many of the best players and clans in the world use to visit this event to have fun and compete in the tournaments for 1on1, 2on2 and 4on4.
			</li>
		</list>
		<h>Various</h>				
		<list>
			<li>
				<h><a href="http://www.udpsoft.com/eye/">The All-Seeing Eye</a></h>
				Looking for a good server to play QW on? Or maybe you just want to spectate all the big hot shots playing? This is one of the best server browsers that supports QW.
			</li>
			<li>
				<h><a href="http://www.challenge-tv.com/">Challenge-TV</a></h>
				All the QW demos you ever wanted. You name it, they got it. They host other games' demos as well but those are boring.
			</li>
		</list>
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/dm6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - DM6: The Dark Zone</title>
		<date>2003-10-07</date>
	</head>
	<body>
		<h align="center">DM6: The Dark Zone</h>
		<br />
		<h>Introduction</h>
		<p>The Dark Zone has always been a classic 1on1 and 2on2 map. Its popularity as a map for teamplay differs alot depending on your location on the globe. While it is a true test of raw skills (aim, movement and predictions) for some, it is a messy chaos for others. Usually a match here is very action packed and exciting for the players, while watching a match here can be quite boring because of the frag, frag, kill, frag, kill, frag, frag style. DM6 is a very good map to play for less experienced players because it's easy to understand and play in comparison to the other classic teamplay maps.</p>
		<br />
		<h>Items available</h>			
			<h>Weapons</h>
			<list>
				<li>2 Rocket Launchers</li>
				<li>1 Lightning Gun</li>
				<li>1 Grenade Launcher</li>
				<li>1 Super Nailgun</li>
				<li>1 Super Shotgun</li>
				<li>1 Nailgun</li>
			</list>
			<h>Armor</h>
			<list>
				<li>1 Red Armor</li>
				<li>1 Green Armor</li>
			</list>
			<h>Powerups</h>
			<list>
				<li>1 Ring of Shadows magic</li>
				<li>1 Megahealth</li>
			</list>
			<br />
			<h>Important areas</h>
			<p>All games on DM6 evolve around controlling the RA area. Once that area is cleared, control is extended to the other parts of the map. Together with the RA you control one of the two RLs. The second one is on the other side of the map in a small room together with the megahealth. In the central area all other areas are connected on two different levels. The GL sits on the upper ledge and a shootable platform reveals the entrance to the LG room with the Ring.</p>
			<list>
			<li>
				<h>RA</h>
				The RA is located on the upper ledge of this area. Some stairs opposing the armor lead onto that ledge. Right in front of the armor, the RL can be picked up at the ground level. Under the stairs there is also the SSG. 
				Three ways lead out of this area. A small hallway across the RA leads into the center area, just like a longer and wider one. The upper ledge leads to the GL area but a gap along the side allows to drop down to the ground level. Right behind the RA, a respawn point is hidden in a tiny passage with two exits.
			</li>
			<li>
				<h>GL</h>
				From the ledge of the RA, a slope leads up to the GL. A wide circular ledge hovers high over the central part of the map. 
				Across the opening, a hallway leads to the stairs with the GA. On one side of the ledge there is a respawn point in the walls, on the other side there are some healthpacks. Looking down here gives a good view on most of the entrances the central area holds: the three ways to the RA, the upper and lower hallway to the stairs, the entrance to the LG and the tube to the megahealth room. The central teleporter can easily be jumped into from here.
			</li>			
			<li>
				<h>GA stairs</h>
				Two long flights of stairs along two walls of the room lead downwards. Both a SNG and the GA are located on the stairs. In the middle of the room there is a teleporter leading into the megahealth room. Next to the teleport, the only pack of rockets on this map is positioned. In a corner, another respawn point is hidden. 
				Besides the upper hallway to the GL, there is another one leading back to the center below the stairhead. The teleport serves as the exit for all other teleporters on the map.
			</li>			
			<li>
				<h>Megahealth</h>
				This is a small room that contains the second RL as well as the Megahealth. They are both right in front of the teleporter which goes back to the GA stairs. 
				A 'tube' leads from this room to the central area.
			</li>			
			<li>
				<h>Center</h>
				This center area interconnects all the other rooms. 
				In the middle of this rather large space, another teleporter leads to the teleporter in the GA room. In front of the tele lies the flimsy NG. Behind the teleporter is the secret entrance to the LG corridor.
			</li>				
			<li>
				<h>LG corridor</h>
				This secret corridor can be accessed by shooting a floorplate in the central area. Besides the LG and some ammo, the Ring also appears here. The teleporter leads back to the central area.
			</li>			
			</list>
			<h>Popular shortcuts</h>
			<p>The most common shortcuts are of course all sorts of rocketjumps up to the RA. Taking the stairs instead is slow and deadly. Skilled rocketjumpers can perform flat but long jumps form the long entrance directly onto the armor, often surprising the RA guards Multiple use of teleporters is also often used as shortcut. This "double' teleporting' sometimes results in telefragged teammates though. Bunnyhopping and especially adding speed to them through rocketjumps has also become common. For example it is possible to master the gap in the GL area with just one jump this way.</p>
			<p>One of the less common shortcuts involves a bug with the Ligthning gun platform. When someone hits it with the LG, it will go up in the air for a glimps of a second. With the right timing you can rocketjump to the upper ledge near the GL. A direct rocketjump from the center floor is very difficult and not usually attempted in matches.</p>
			<h>Basic strategies</h>
			<p>Both in teamplay and duel the basic strategy is to control and take the RA. Usually one or two guys camp there. Camping the other rocketlauncher is also a key to win this map. The fourth member of a team ideally covers some of the entrances (and respawn points) in the center from the GL area.</p>
			<p>Every five minutes the ring respawns and it is often used to attack and overtake RA. Due to the nature and the size of the map it is not possible to really lock it down except when the skill gap between the teams is very large. Therefore, games here are usually quite exciting with control and lead changing constantly.</p>	
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/important_commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - Important commands</title>
		<date>2004-10-16</date>
	</head>
	<body>
		<h align="center">Important commands</h>
		<br />
		<p>The most important and commonly used commands which are used while playing QW will be explained below. All have to be entered into the console which can be brought up by the tilde (~) key:</p>
		
		<list>
			<li>
				<h>connect [ip:port]</h>
				The "connect" command is always followed by an IP address/hostname and will connect you to the server specified. Sometimes you also have to add the port after the IP address unless the server runs on the default port 27500. You can paste addresses for example from IRC into the QW console by pressing Ctrl+V at the same time. Examples:
				<pre>
				connect 160.45.32.200:27501
				connect archroy.barrysworld.com
				</pre>
			</li>
			<li>
				<h>disconnect</h>
				This command is needed to disconnect you from a server.
			</li>
			<li>
				<h>reconnect</h>
				You need this to reconnect to the last server you were connected to because you either timed out, QW loaded the map but you didn't spawn or something else happened. You also need to reconnect if you want to changer into spectator mode or vice versa.
			</li>
			<li>
				<h>spectator 0|1</h>
				If you want to spectate a game you have to set spectator to 1 before connecting or reconnecting to a server. If you want to connect as player you have to set it to 0 (default) before connecting or reconnecting to a server.
			</li>	
			<li>
				<h>join</h>
				If you are already on a server as a spectator and want to join the game, just type this command instead of writing <color>spectator 0</color> followed by <color>reconnect</color>. Faster and easier!
			</li>
			<li>
				<h>observe</h>
				Works the same way as the <color>join</color> command. If you are playing on a server and want to reconnect as a spectator, use this command.
			</li>
			<li>
				<h>cl_chasecam 0|1</h>
				<h>cl_hightrack 0|1</h>
				There are different modes of spectating. When chasecam is set to 0 you can float around the map yourself with the movement keys and position yourself to any area you are interested to. When chasecam is set to 1 the cam will follow one player. You can use the attack/jump button to change the tracked player and wether you see everything through the players eyes or wether the cam is positioned above him. If hightrack is turned on the camera will always follow the player who has the most frags.
			</li>
			<li>
				<h>password [x]</h>
				Some servers are password protected. If you happen to know the password you have to type password and after that the password itself before connecting to that server. Sometimes the observer spots on a server are also password protected and the password is submitted in a different way. Type spectator followed by the password in the console before connecting. Examples:
				<pre>
				password hejsan (then connect ip:port)
				spectator pylly (then connect ip:port)
				</pre>
			</li>
			<li>
				<h>quit</h>
				If you are fed up with playing just type this at the console and you are relieved...
			</li>
			<li>
				<h>team [x]</h>
				When playing a team game you have to set your team by typing "team" followed by the teamname which can be up to four letters long. Note that teamnames are case sensitive and can contain spaces and special characters. Examples:
				<pre>
				team red (puts you in team red)
				team " red" (puts you in team _red, therefore the ")
				team "^-er^-" (puts you in team -er- (putting the ^ before a character will make it appear red instead of gray))
				</pre>
			</li>
			<li>
				<h>sensitivity [x]</h>
				This controls the sensitivity at which your mouse works and has to be followed by a number. Example:
				<pre>sensitivity 5.2</pre>
			</li>
			<li>
				<h>fov [x]</h>
				This command determines your field of view. Allowed values range from 10 to 170. Much more than 130 and less than 90 are not very useful though.
			</li>																										
		</list>
		<h>Kombat Teams/KTPro commands</h>
		<p>Most QW servers run a mod called either Kombat Teams or KTPro (KTPro is a newer and improved version of the older Kombat Teams). These are modifications of the QW server designed specifically to make competitive play more easy (no changes to the general gameplay have been made though). The most important commands on these servers are explained below:</p>
		<list>
			<li>
				<h>ready</h>
				Everyone has to type this before the countdown that starts the game begins.
			</li>
			<li>
				<h>break</h>
				This will either stop the countdown or, if a match is going on, vote to stop the match. Matches will only be stopped if the majority of players votes for breaking.
			</li>
			<li>
				<h>timeup</h>
				<h>timedown</h>
				Change the timelimit by 5 min increments.
			</li>
			<li>
				<h>dmm[1-7]</h>
				Changes the deathmatch mode. The usual deathmatch modes are dmm1 (standard in 4on4) and dmm3 (standard in 1on1 and 2on2). All the different modes are explained below:
				<pre>
				dmm1 = weapons disappear when you take them and return after 30 seconds, ammo returns after 20 seconds. 
				dmm2 = as described above, but no health or armor on maps. 
				dmm3 = weapons stay when you take them, ammo returns after 20 seconds. 
				dmm4 = spawn with 255 armor and health, plus all weapons except for the grenade launcher.
				</pre>
			</li>
			<li>
				<h>powerups</h>
				Toggle powerups on or off.
			</li>
			<li>
				<h>[mapname]</h>
				You can vote for a mapchange by simply typing in the name of the new map you wish to play (it has to be supported by the server though). A majority of all players on the server has to vote for the map to change.
			</li>
			<li>
				<h>whonot</h>
				Check who has already gone ready and who is holding things up.
			</li>
			<li>
				<h>commands</h>
				<h>options</h>
				<h>cmd help</h>
				Use these three to get a more detailed list of commands and settings available in KTeam/KTpro.
			</li>
		</list>																			
	</body>
</document>

=== miltonizer/miltons_twitch_quake/ezquake/help/manual/external_resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/document.xsl"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/document.xsd">
	<head>
		<title>ezQuake Manual - External resources</title>
		<date>2009-07-04</date>
	</head>
	<body>
		<br />
		<p>Before we move on to the core of this guide, it is important that you know some places where to get additional help on QW, in case you need more information or are just confused. There are a few other sites on the web offering help about QW. You can also find lots of experienced QW players on IRC (check channels below), just ask us.</p>
		<br />
		<h>Guides and forums</h>
		<list>
			<li>
				<h><a href="http://www.nQuake.com/">nQuake</a></h>
				Complete Quakeworld package. Contains everything you need to play (except pak1.pak) with good default configs, textures and other game related files which are not available in the regular ezQuake package.
			</li>
			<li>
				<h><a href="http://ezQuake.SF.net/">ezQuake</a></h>
				The ezQuake website has documentation that explains most of ezQuake's features, all the necessary files and more. There is also a RFE (Request FeaturE) page and a bug report page.
			</li>
			<li>
				<h><a href="http://ezQuake.SF.net/docs/">ezQuake Documentation</a></h>
				Explains all of ezQuake's variables, console commands, command line parameters and more. 
			</li>
			<li>
				<h><a href="http://www.quakeworld.nu/forum/">QuakeWorld.nu Forum</a></h>
				For any questions related to QW. See the Help or Client Talk sections.
			</li>
			<li>
				<h><a href="http://www.quaketerminus.com/quakebible/">Thresh's Quake Bible</a></h>
				Written by the master himself; Dennis Fong alias Thresh. This comprehensive guide to Quake (NetQuake) goes thoroughly every aspect of the game from game controls to rocket jumping and advanced team strategy. Although many of the strategies explained are a bit outdated, it's still a good read that every true Quaker should have read!  
			</li>
			</list>
		<h>IRC channels</h>
			<list>
			<li>
				<h>#ezQuake (IRC.QuakeNet.org)</h>
				The official ezQuake IRC channel. This is the best place to ask if your question is directly related to ezQuake. It is also a place to discuss new features which are under development. 
			</li>
			<li>
				<h>#QuakeWorld (IRC.QuakeNet.org)</h>
				The largest QW community channel on QuakeNet and also the official channel for the QuakeWorld.nu website. You'll always find experienced people here who are willing to help. 
			</li>
			<li>
				<h>#QWrookie (IRC.QuakeNet.org)</h>
				Quakeworld channel for beginning players. If you are looking for rookie opponents, configuration tips or want to ask a beginner question this is the place to be.
			</li>
			<li>
				<h>#QWPlayers (IRC.EnterTheGame.com)</h>
				North American QW community channel. 
			</li>
			<li>
				<h>#Besmella (IRC.EnterTheGame.com)</h>
				Australian QW community channel.
			</li>
			</list>	
	</body>
</document>
